### ISSUE TITLE
Setup a new node and express project

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-back-end#1]
# Description 
Setup a new node project with express 

# Tasks
- [ ] look into using typescript 
- [ ] setup node and express
- [ ] install axios
- [ ] dev dependency: nodemon
